[
    {
        "file_id": "4",
        "service": "uber_eats",
        "task_url": "https://production.knotapi.com/dashboard/resources/bots/23556542",
        "steps": [
            "Entering connect",
            "Using cookies integration",
            "Importing session",
            "csid from .payments.uber.com is present , we need to filter the cookies",
            "Filtering the cookies...",
            "Cookies_filtered lenght 120",
            "Cookies sanitized",
            "Checking cookies.",
            "Checking cookies response.",
            "Valid cookies.",
            "Entering card switcher",
            "Running CoF pre-check",
            "Running Card Switcher",
            "Getting payment profile uuid",
            "Payment methods recieved",
            "Payment list recieved",
            "attempt 0",
            "Card already added, response: failure",
            "Getting payment profile uuid",
            "Payment methods recieved",
            "{'current_card_last_four': '7928'}",
            "Card is reflected on the site",
            "Running Card Verifier",
            "Exported session",
            "Closed client",
            "Bot finished"
        ],
        "status": "success",
        "error_message": null,
        "error_details": null
    },
    {
        "file_id": "2",
        "service": "uber_eats",
        "task_url": "https://production.knotapi.com/dashboard/resources/bots/23545113",
        "steps": [
            "Entering connect",
            "Using integration",
            "Importing session",
            "Sanitized successfully",
            "Checking response.",
            "Valid session.",
            "Entering card switcher",
            "Running CoF pre-check",
            "Running Card Switcher",
            "Getting payment profile uuid",
            "Payment methods recieved",
            "Payment list recieved",
            "attempt 0",
            "Card already added, response: failure",
            "Getting payment profile uuid",
            "Payment methods recieved",
            "{'current_card_last_four': '7928'}",
            "Card is reflected on the site",
            "Running Card Verifier",
            "Exported session",
            "Closed client",
            "Bot finished"
        ],
        "status": "success",
        "error_message": null,
        "error_details": null
    },
    {
        "file_id": "3",
        "service": "uber_eats",
        "task_url": "https://production.knotapi.com/dashboard/resources/bots/23556430",
        "steps": [
            "Entering connect",
            "Using cookies integration",
            "Importing session",
            "Cookies_filtered lenght 109",
            "Cookies sanitized",
            "Checking cookies.",
            "Checking cookies response.",
            "Valid cookies.",
            "Entering card switcher",
            "Running CoF pre-check",
            "Running Card Switcher",
            "Getting payment profile uuid",
            "Payment methods recieved",
            "Payment list recieved",
            "attempt 0",
            "Getting payment profile uuid",
            "Payment methods recieved",
            "{'current_card_last_four': '8775'}",
            "Uber bug, API Returned success but card is not reflected",
            "Running Card Verifier",
            "Exported session",
            "Closed client",
            "Bot finished"
        ],
        "status": "success",
        "error_message": null,
        "error_details": null
    },
    {
        "file_id": "1",
        "service": "uber_eats",
        "task_url": "https://production.knotapi.com/dashboard/resources/bots/26732612",
        "steps": [
            "Entering connect",
            "Starting with_timeout execution",
            "Importing session",
            "Cookies_filtered lenght 128",
            "Cookies sanitized",
            "Checking cookies.",
            "Checking cookies response.",
            "Valid cookies.",
            "with_timeout completed successfully",
            "Entering card switcher",
            "Running CoF pre-check",
            "Starting with_timeout execution",
            "with_timeout completed successfully",
            "Running Card Switcher",
            "Starting with_timeout execution",
            "Some of the cookies required to update the card are not present to continue with the process.",
            "Update card error",
            "Exported session",
            "Closed client",
            "mark_as_failed"
        ],
        "status": "failed",
        "error_message": "commons.exceptions.exceptions.CardErrorException",
        "error_details": {
            "type": "commons.exceptions.exceptions.CardErrorException",
            "message": null,
            "location": "File \"/workspace/main.py\", line 350, in handler_async",
            "full_trace": [
                "Traceback (most recent call last):",
                "File \"/workspace/main.py\", line 350, in handler_async",
                "result = await integration.handle(payload)",
                "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                "File \"/workspace/src/integrations/index.py\", line 225, in handle",
                "raise error",
                "File \"/workspace/src/integrations/index.py\", line 132, in handle",
                "await with_timeout(",
                "File \"/workspace/src/util/helpers.py\", line 286, in with_timeout",
                "result = await asyncio.wait_for(callback, ms / 1000)",
                "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                "File \"/layers/google.python.runtime/python/lib/python3.11/asyncio/tasks.py\", line 489, in wait_for",
                "return fut.result()",
                "^^^^^^^^^^^^",
                "File \"/workspace/src/integrations/uber_eats/index.py\", line 63, in card_switcher",
                "await zipRetry(",
                "File \"/workspace/src/util/helpers.py\", line 116, in zipRetry",
                "raise error",
                "File \"/workspace/src/util/helpers.py\", line 89, in zipRetry",
                "return await callback()",
                "^^^^^^^^^^^^^^^^",
                "File \"/workspace/src/integrations/uber_eats/index.py\", line 53, in update_card",
                "return await self.client.update_card(",
                "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                "File \"/workspace/vendor/ubereats/client.py\", line 261, in update_card",
                "await self._api.add_card(",
                "File \"/workspace/vendor/ubereats/api/desktop_web.py\", line 404, in add_card",
                "raise e",
                "File \"/workspace/vendor/ubereats/api/desktop_web.py\", line 364, in add_card",
                "raise CardErrorException",
                "commons.exceptions.exceptions.CardErrorException"
            ]
        }
    }
]